/*
*This code is generated by sworks
*/

class registerFragement {

   
   public void register {
    //ToDO business logic will go here
}public void udpate {
    //ToDO business logic will go here
}


}