/*
*This code is generated by sworks
*/

class registerFragement {

   
   public void register {
    //ToDO business logic will go here

    user.register()
}public void udpate {
    //ToDO business logic will go here

    user.update()
}


}